### ISSUE TITLE
GitHub Presente ES March 2023 Tracking issue

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#37]
**Date of event** : _March, 02_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Host | Denny | Vicente |

| Task| Status| Details |
| --- | --- | --- |
| Speakers invitados | ✅  | dorian.hidalgo@gmail.com &  carla.mamani_chavez@studentambassadors.com |
| Speaker Confirmation 1 | ✅  |  |
| Speaker Confirmation 2  | ✅   |  |
| Generate event - StreamYard | ✅  | [https://streamyard.com/7y9pj9k7ed](https://www.google.com/url?q=https://streamyard.com/7y9pj9k7ed&sa=D&source=calendar&usd=2&usg=AOvVaw2Szemv21HoawvwSoZxeATi) |
| Create event on Meetup |  ✅  | https://www.meetup.com/githublatam/events/291162657/ |
| Social media poster design | ✅   |  |
| Create short links |   |  |
| Block for date and time event | ✅  |  |
| Tech Check with Speaker 1 |  ✅  | Jueves 23 / 1:00  |
| Tech Check with Speaker 2 |  ✅   | Viernes 24 / 5:00  |
| Create Slide (deck) |  |   |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by lizarragadev** [comment]
Hola @AndreaGriffiths11  y @DennyPerez18  les comento que ya hice los videos para este Meetup. (Quizá luego me olvido, mejor lo hago ahora, si ya hay ficha para Abril, también lo hago).

Todo lo colocaré en una misma carpeta en Google Drive:

- Intros de Speakers, video para estados y video para Twitter Marzo: [Enlace](https://drive.google.com/drive/folders/1r8h_DZabYz9gnzvhYCHuS-KYJVuc7gZg?usp=sharing)  (Adicioné un video más en formato cuadrado para Twitter, ya que vi que lo utilizaron el anterior en Twitter).
- Además adicioné una transición para utilizar al momento de sacar de escena a un invitado y no sea tan brusca su salida, la transición son unos 3 segundos nada más, [acá el enlace junto a los countdowns](https://drive.google.com/drive/folders/1Tjyp0oxKmZ1fwDRFdGnnFQIthitpM9MC?usp=sharing)

Quedo atento a que más puedo ayudar, todos estos videos ya están los templates y para todo el año solo será cambiar imágenes, textos y renderizar, así que todo es mecánico, por lo que si necesitan ayuda en otras cosas yo atento acá.

> la info de los videos lo estoy sacando del Meetup :) horas, zonas horarias, fechas, etc.

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 Hola. Te parece si comienzo el contacto para el TecCheck con Dorian y Carla?
Para también comenzar a anunciarlos en las redes a principio de la semana próxima.

**Comment by AndreaGriffiths11** [comment]
Si porfa 🙏🏽
Mil gracias

**Comment by lizarragadev** [comment]
> @lizarragadev muchas gracias por los videos!

Con gusto! Ya pendiente del siguiente mes para hacer los videos :)

**Comment by DennyPerez18** [comment]
Done:
https://www.youtube.com/watch?v=GUWWtULA-3w
