### ISSUE TITLE
GitHub Presente ES April 2023 Tracking issue

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#38]
**Date of event** : _May, 25_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speakers invitados | psolenny@gmail.com & leifer33@gmail.com |  |
| Speaker Confirmation 1 |  |  |
| Speaker Confirmation 2  |   |  |
| Generate event - StreamYard |  |  |
| Create event on Meetup |    |  |
| Social media poster design |   |  |
| Create short links |   |  |
| Block for date and time event |   |  |
| Tech Check with Speaker 1 |   |   |
| Tech Check with Speaker 2 |    |   |
| Create Slide (deck) |  |   |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by DennyPerez18** [comment]
![abr-23](https://user-images.githubusercontent.com/38770890/225441134-bcf255fb-4828-418a-9afe-235949cd56c6.png)

**Comment by lizarragadev** [comment]
Hola @DennyPerez18 y @AndreaGriffiths11 , una disculpa la demora, estuve con unos inconvenientes de salud en casa y anduve desconectado, ahora si volví, acabo de hacer los assets multimedia para el meetup de Abril.

[Acá el enlace](https://drive.google.com/drive/folders/1ta8pZ1rjFsZ5vj9KSdJTazl0TsbZdmn6?usp=sharing)

Quedo atento a otra novedad o requerimiento que necesiten que pueda apoyar.

**Comment by AndreaGriffiths11** [comment]
Mil gracias @lizarragadev

**Comment by DennyPerez18** [comment]
> Hola @DennyPerez18 y @AndreaGriffiths11 , una disculpa la demora, estuve con unos inconvenientes de salud en casa y anduve desconectado, ahora si volví, acabo de hacer los assets multimedia para el meetup de Abril.
> 
> [Acá el enlace](https://drive.google.com/drive/folders/1ta8pZ1rjFsZ5vj9KSdJTazl0TsbZdmn6?usp=sharing)
> 
> Quedo atento a otra novedad o requerimiento que necesiten que pueda apoyar.

Ayy! Muchisimas gracias Gus, Espero que ya ande todo bien 🙏
