### ISSUE TITLE
GitHub Presente ES May 2023 Tracking issue

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#39]
**Date of event** : _May, 04_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 

**Andres Pineda:** A11y beyond screen readers: Making apps more accessible

**Valeria Tafoya:** Habilidades digitales orientadas a la misión
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speakers Invitados | ✅ | pineda.andres@gmail.com & valeriatafoya.dv@gmail.com |
| Speaker Confirmation 1 |  |  |
| Speaker Confirmation 2  |   |  |
| Generate event - StreamYard |  |  |
| Create event on Meetup |    |  |
| Social media poster design |   |  |
| Create short links |   |  |
| Block for date and time event | ✅ |  |
| Tech Check with Speaker 1 |   |   |
| Tech Check with Speaker 2 |    |   |
| Create Slide (deck) |  |   |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by lizarragadev** [comment]
Hola @DennyPerez18 y @AndreaGriffiths11 

Acá retomando mi equipo para ponerme al día poco a poco, una consulta, estos dos invitados están confirmados?
Para proceder a hacer sus intros.

Gracias.

**Comment by DennyPerez18** [comment]
@lizarragadev ya este meetup paso. Voy a poner los detalles del proximo Meetup que es el 8 de Junio en este issue: https://github.com/githubpresente/Meetup-ES/issues/40

**Comment by DennyPerez18** [comment]
YouTube: https://www.youtube.com/live/RL-DZEdxN0M?feature=share
